@startuml
'== Formatting ==
hide empty description
skinparam Arrow {
  FontSize 9
}
skinparam State {
  FontSize 12
}

'== Default messages ==
!$Timeout = Timeout
!$No = No
!$Yes = Yes

'== Interfaces ==
!$RTx = RTx

'== Messages ==
!$RTx_ConnectReq = $RTx + ":" + ConnectReq
!$RTx_ConnectedInd = $RTx + ":" + ConnectedInd
!$RTx_DisconnectInd = $RTx + ":" + DisconnectInd

'== Component ==
state component as "Node" {
state START <<start>> #000000

'== States ==
state Advertising
state Connecting
state ServerConnected as "Server\nConnected"

'== Choice-points ==
state CP_Whitelisted as "Is Server\nWhitelisted?"

'== Transitions ==
START --> Advertising
Advertising --> Advertising : $Timeout
Advertising --> CP_Whitelisted : $RTx_ConnectReq\n$RTx_ConnectedInd
CP_Whitelisted --> Connecting : $Yes
CP_Whitelisted -up--> Advertising : $No
Connecting --> Advertising : $Timeout
Connecting -> ServerConnected : $RTx_ConnectedInd
ServerConnected --> Advertising : $RTx_DisconnectInd\n$Timeout
ServerConnected --> ServerConnected : $RTx_ConnectedInd

'== Footer ==
}
@enduml